### ISSUE TITLE
支付宝插件run failed的bug及处理

### ISSUE THREAD

**Issue by shanchuang123** [zhongdom/eros-plugin-iOS-alipay#1]
按照教程会报以下错误:

错误1:文件AppDelegate.m报错,  Use of undeclared identifier 'AlipaySDK'
解决:  在#import "AppDelegate.h"下一行增加引入#import <AlipaySDK/AlipaySDK.h>

错误2:插件内文件ZDAliPayModule.m报错,WeexPluginLoader/WeexPluginLoader.h file not found
解决: 代码 #import <WeexPluginLoader/WeexPluginLoader.h> 替换成 #import <WeexPluginLoader/WeexPluginLoader/WeexPluginLoader.h>

错误3:插件内文件ZDAliPayModule.h报错,WXModuleProtocol.h file not found with <angled> include;
解决:代码 #import <WXModuleProtocol.h> 替换成 #import <WeexSDK/WeexSDK.h>

以上代码替换后可以成功运行并支付

**Comment by zhongdom** [comment]
已修复
