### ISSUE TITLE
在底层已经按照教程配置了白名单 URL，但是在APP端死活木反应

### ISSUE THREAD

**Issue by fangniuge** [zhongdom/eros-plugin-iOS-alipay#5]
尊敬的作者，我们在底层已经按照教程配置了白名单 URL，但是在ios APP端死活木反应，是怎么回事呢？说明服务器写的支付宝接口，在安卓端都调用正常。

**Comment by zhongdom** [comment]
你在 `ZDAliPayModule.m` 文件的第26行打个断点，如果不能触发这个断点，说明还没走到支付宝支付这一步，你的js那边报错了，排查一下。如果还是不行，方便的话，联系方式，我给你远程看一下

**Comment by fangniuge** [comment]
嗯 下过断点了，。都木走进去，方便远程。

**Comment by zhongdom** [comment]
你没有到断点，那就是你js端的问题，看看是否函数名写错了

**Comment by fangniuge** [comment]
你联系我吧 我qq 11221077.都按照教程严格检查了
